SEXP _get_a(SEXP sArgList) const;
SEXP _set_a(SEXP arg_a, SEXP sArgList);
SEXP _get_nt_a(SEXP sArgList) const;
SEXP _set_nt_a(SEXP arg_a, SEXP sArgList);
SEXP _get_amat() const;
SEXP _set_amat(SEXP arg_amat);
SEXP _get_by(SEXP sArgList) const;
SEXP _set_by(SEXP arg_by, SEXP sArgList);
SEXP _get_nt_by(SEXP sArgList) const;
SEXP _set_nt_by(SEXP arg_by, SEXP sArgList);
SEXP R_internal_calc_probs(SEXP dummy, bool bTranslate);
SEXP R_calc_probs(SEXP dummy);
SEXP R_nt_calc_probs(SEXP dummy);
SEXP _get_first_y() const;
SEXP _set_first_y(SEXP arg_first_y);
SEXP _get_first_y_sample() const;
SEXP _set_first_y_sample(SEXP arg_first_y_sample);
SEXP _get_inv_totfec_ys(SEXP sArgList) const;
SEXP _set_inv_totfec_ys(SEXP arg_inv_totfec_ys, SEXP sArgList);
SEXP _get_nt_inv_totfec_ys(SEXP sArgList) const;
SEXP _set_nt_inv_totfec_ys(SEXP arg_inv_totfec_ys, SEXP sArgList);
SEXP _get_inv_totfec_ysb1_pars(SEXP sArgList) const;
SEXP _set_inv_totfec_ysb1_pars(SEXP arg_inv_totfec_ysb1_pars, SEXP sArgList);
SEXP _get_nt_inv_totfec_ysb1_pars(SEXP sArgList) const;
SEXP _set_nt_inv_totfec_ysb1_pars(SEXP arg_inv_totfec_ysb1_pars, SEXP sArgList);
SEXP _get_isamp_POP(SEXP sArgList) const;
SEXP _set_isamp_POP(SEXP arg_isamp_POP, SEXP sArgList);
SEXP _get_nt_isamp_POP(SEXP sArgList) const;
SEXP _set_nt_isamp_POP(SEXP arg_isamp_POP, SEXP sArgList);
SEXP _get_jsamp_POP(SEXP sArgList) const;
SEXP _set_jsamp_POP(SEXP arg_jsamp_POP, SEXP sArgList);
SEXP _get_nt_jsamp_POP(SEXP sArgList) const;
SEXP _set_nt_jsamp_POP(SEXP arg_jsamp_POP, SEXP sArgList);
SEXP _get_last_y() const;
SEXP _set_last_y(SEXP arg_last_y);
SEXP R_internal_lglk(SEXP pars, bool bTranslate);
SEXP R_lglk(SEXP pars);
SEXP R_nt_lglk(SEXP pars);
SEXP R_internal_LGLK_BPARS(SEXP pars, SEXP parsb1_pars, SEXP lglkb1_pars, bool bTranslate);
SEXP R_LGLK_BPARS(SEXP pars, SEXP parsb1_pars, SEXP lglkb1_pars);
SEXP R_nt_LGLK_BPARS(SEXP pars, SEXP parsb1_pars, SEXP lglkb1_pars);
SEXP R_internal_make_data_summaries(bool bTranslate);
SEXP R_make_data_summaries();
SEXP R_nt_make_data_summaries();
SEXP _get_N0_f() const;
SEXP _set_N0_f(SEXP arg_N0_f);
SEXP _get_n0_fb1_pars() const;
SEXP _set_n0_fb1_pars(SEXP arg_n0_fb1_pars);
SEXP _get_N0_m() const;
SEXP _set_N0_m(SEXP arg_N0_m);
SEXP _get_n0_mb1_pars() const;
SEXP _set_n0_mb1_pars(SEXP arg_n0_mb1_pars);
SEXP _get_n_comps_ytbsm(SEXP sArgList) const;
SEXP _set_n_comps_ytbsm(SEXP arg_n_comps_ytbsm, SEXP sArgList);
SEXP _get_nt_n_comps_ytbsm(SEXP sArgList) const;
SEXP _set_nt_n_comps_ytbsm(SEXP arg_n_comps_ytbsm, SEXP sArgList);
SEXP _get_n_par() const;
SEXP _set_n_par(SEXP arg_n_par);
SEXP _get_n_POP() const;
SEXP _set_n_POP(SEXP arg_n_POP);
SEXP _get_n_samp() const;
SEXP _set_n_samp(SEXP arg_n_samp);
SEXP _get_N_ys(SEXP sArgList) const;
SEXP _set_N_ys(SEXP arg_N_ys, SEXP sArgList);
SEXP _get_nt_N_ys(SEXP sArgList) const;
SEXP _set_nt_N_ys(SEXP arg_N_ys, SEXP sArgList);
SEXP _get_n_ysb1_pars(SEXP sArgList) const;
SEXP _set_n_ysb1_pars(SEXP arg_n_ysb1_pars, SEXP sArgList);
SEXP _get_nt_n_ysb1_pars(SEXP sArgList) const;
SEXP _set_nt_n_ysb1_pars(SEXP arg_n_ysb1_pars, SEXP sArgList);
SEXP R_internal_next_param(bool bTranslate);
SEXP R_next_param();
SEXP R_nt_next_param();
SEXP _get_nextpari() const;
SEXP _set_nextpari(SEXP arg_nextpari);
SEXP R_internal_populate(SEXP dummy, bool bTranslate);
SEXP R_populate(SEXP dummy);
SEXP R_nt_populate(SEXP dummy);
SEXP _get_Pr_PO_ytbs(SEXP sArgList) const;
SEXP _set_Pr_PO_ytbs(SEXP arg_Pr_PO_ytbs, SEXP sArgList);
SEXP _get_nt_Pr_PO_ytbs(SEXP sArgList) const;
SEXP _set_nt_Pr_PO_ytbs(SEXP arg_Pr_PO_ytbs, SEXP sArgList);
SEXP _get_pr_po_ytbsb1_pars(SEXP sArgList) const;
SEXP _set_pr_po_ytbsb1_pars(SEXP arg_pr_po_ytbsb1_pars, SEXP sArgList);
SEXP _get_nt_pr_po_ytbsb1_pars(SEXP sArgList) const;
SEXP _set_nt_pr_po_ytbsb1_pars(SEXP arg_pr_po_ytbsb1_pars, SEXP sArgList);
SEXP _get_roi() const;
SEXP _set_roi(SEXP arg_roi);
SEXP _get_roib1_pars() const;
SEXP _set_roib1_pars(SEXP arg_roib1_pars);
SEXP _get_sex(SEXP sArgList) const;
SEXP _set_sex(SEXP arg_sex, SEXP sArgList);
SEXP _get_nt_sex(SEXP sArgList) const;
SEXP _set_nt_sex(SEXP arg_sex, SEXP sArgList);
SEXP _get_sqrt_Pr_PO_ytbs(SEXP sArgList) const;
SEXP _set_sqrt_Pr_PO_ytbs(SEXP arg_sqrt_Pr_PO_ytbs, SEXP sArgList);
SEXP _get_nt_sqrt_Pr_PO_ytbs(SEXP sArgList) const;
SEXP _set_nt_sqrt_Pr_PO_ytbs(SEXP arg_sqrt_Pr_PO_ytbs, SEXP sArgList);
SEXP R_internal_sqrt_probs(SEXP pars, bool bTranslate);
SEXP R_sqrt_probs(SEXP pars);
SEXP R_nt_sqrt_probs(SEXP pars);
SEXP _get_tcap(SEXP sArgList) const;
SEXP _set_tcap(SEXP arg_tcap, SEXP sArgList);
SEXP _get_nt_tcap(SEXP sArgList) const;
SEXP _set_nt_tcap(SEXP arg_tcap, SEXP sArgList);
SEXP _get_temp_pars(SEXP sArgList) const;
SEXP _set_temp_pars(SEXP arg_temp_pars, SEXP sArgList);
SEXP _get_nt_temp_pars(SEXP sArgList) const;
SEXP _set_nt_temp_pars(SEXP arg_temp_pars, SEXP sArgList);
SEXP _get_temp_parsb1_pars(SEXP sArgList) const;
SEXP _set_temp_parsb1_pars(SEXP arg_temp_parsb1_pars, SEXP sArgList);
SEXP _get_nt_temp_parsb1_pars(SEXP sArgList) const;
SEXP _set_nt_temp_parsb1_pars(SEXP arg_temp_parsb1_pars, SEXP sArgList);
SEXP R_internal_unpack(SEXP pars, bool bTranslate);
SEXP R_unpack(SEXP pars);
SEXP R_nt_unpack(SEXP pars);
SEXP _get_ymat_atmost(SEXP sArgList) const;
SEXP _set_ymat_atmost(SEXP arg_ymat_atmost, SEXP sArgList);
SEXP _get_nt_ymat_atmost(SEXP sArgList) const;
SEXP _set_nt_ymat_atmost(SEXP arg_ymat_atmost, SEXP sArgList);
