static const R_CallMethodDef extMethods[] = 
{
  {"_Bd.destroy", (DL_FUNC)&Bd_destroy, 1},
  {"_Bd.create", (DL_FUNC)&Bd_create, 12},
  {"_Bd.get.a", (DL_FUNC)&Bd_get_a, 2},
  {"_Bd.set.a", (DL_FUNC)&Bd_set_a, 3},
  {"_Bd.get.nt.a", (DL_FUNC)&Bd_get_nt_a, 2},
  {"_Bd.set.nt.a", (DL_FUNC)&Bd_set_nt_a, 3},
  {"_Bd.get.amat", (DL_FUNC)&Bd_get_amat, 1},
  {"_Bd.set.amat", (DL_FUNC)&Bd_set_amat, 2},
  {"_Bd.get.by", (DL_FUNC)&Bd_get_by, 2},
  {"_Bd.set.by", (DL_FUNC)&Bd_set_by, 3},
  {"_Bd.get.nt.by", (DL_FUNC)&Bd_get_nt_by, 2},
  {"_Bd.set.nt.by", (DL_FUNC)&Bd_set_nt_by, 3},
  {"_Bd.calc_probs", (DL_FUNC)&Bd_R_calc_probs, 2},
  {"_Bd.nt.calc_probs", (DL_FUNC)&Bd_R_nt_calc_probs, 2},
  {"_Bd.get.first_y", (DL_FUNC)&Bd_get_first_y, 1},
  {"_Bd.set.first_y", (DL_FUNC)&Bd_set_first_y, 2},
  {"_Bd.get.first_y_sample", (DL_FUNC)&Bd_get_first_y_sample, 1},
  {"_Bd.set.first_y_sample", (DL_FUNC)&Bd_set_first_y_sample, 2},
  {"_Bd.get.inv_totfec_ys", (DL_FUNC)&Bd_get_inv_totfec_ys, 2},
  {"_Bd.set.inv_totfec_ys", (DL_FUNC)&Bd_set_inv_totfec_ys, 3},
  {"_Bd.get.nt.inv_totfec_ys", (DL_FUNC)&Bd_get_nt_inv_totfec_ys, 2},
  {"_Bd.set.nt.inv_totfec_ys", (DL_FUNC)&Bd_set_nt_inv_totfec_ys, 3},
  {"_Bd.get.inv_totfec_ysb1_pars", (DL_FUNC)&Bd_get_inv_totfec_ysb1_pars, 2},
  {"_Bd.set.inv_totfec_ysb1_pars", (DL_FUNC)&Bd_set_inv_totfec_ysb1_pars, 3},
  {"_Bd.get.nt.inv_totfec_ysb1_pars", (DL_FUNC)&Bd_get_nt_inv_totfec_ysb1_pars, 2},
  {"_Bd.set.nt.inv_totfec_ysb1_pars", (DL_FUNC)&Bd_set_nt_inv_totfec_ysb1_pars, 3},
  {"_Bd.get.isamp_POP", (DL_FUNC)&Bd_get_isamp_POP, 2},
  {"_Bd.set.isamp_POP", (DL_FUNC)&Bd_set_isamp_POP, 3},
  {"_Bd.get.nt.isamp_POP", (DL_FUNC)&Bd_get_nt_isamp_POP, 2},
  {"_Bd.set.nt.isamp_POP", (DL_FUNC)&Bd_set_nt_isamp_POP, 3},
  {"_Bd.get.jsamp_POP", (DL_FUNC)&Bd_get_jsamp_POP, 2},
  {"_Bd.set.jsamp_POP", (DL_FUNC)&Bd_set_jsamp_POP, 3},
  {"_Bd.get.nt.jsamp_POP", (DL_FUNC)&Bd_get_nt_jsamp_POP, 2},
  {"_Bd.set.nt.jsamp_POP", (DL_FUNC)&Bd_set_nt_jsamp_POP, 3},
  {"_Bd.get.last_y", (DL_FUNC)&Bd_get_last_y, 1},
  {"_Bd.set.last_y", (DL_FUNC)&Bd_set_last_y, 2},
  {"_Bd.lglk", (DL_FUNC)&Bd_R_lglk, 2},
  {"_Bd.nt.lglk", (DL_FUNC)&Bd_R_nt_lglk, 2},
  {"_Bd.LGLK_BPARS", (DL_FUNC)&Bd_R_LGLK_BPARS, 4},
  {"_Bd.nt.LGLK_BPARS", (DL_FUNC)&Bd_R_nt_LGLK_BPARS, 4},
  {"_Bd.make_data_summaries", (DL_FUNC)&Bd_R_make_data_summaries, 1},
  {"_Bd.nt.make_data_summaries", (DL_FUNC)&Bd_R_nt_make_data_summaries, 1},
  {"_Bd.get.N0_f", (DL_FUNC)&Bd_get_N0_f, 1},
  {"_Bd.set.N0_f", (DL_FUNC)&Bd_set_N0_f, 2},
  {"_Bd.get.n0_fb1_pars", (DL_FUNC)&Bd_get_n0_fb1_pars, 1},
  {"_Bd.set.n0_fb1_pars", (DL_FUNC)&Bd_set_n0_fb1_pars, 2},
  {"_Bd.get.N0_m", (DL_FUNC)&Bd_get_N0_m, 1},
  {"_Bd.set.N0_m", (DL_FUNC)&Bd_set_N0_m, 2},
  {"_Bd.get.n0_mb1_pars", (DL_FUNC)&Bd_get_n0_mb1_pars, 1},
  {"_Bd.set.n0_mb1_pars", (DL_FUNC)&Bd_set_n0_mb1_pars, 2},
  {"_Bd.get.n_comps_ytbsm", (DL_FUNC)&Bd_get_n_comps_ytbsm, 2},
  {"_Bd.set.n_comps_ytbsm", (DL_FUNC)&Bd_set_n_comps_ytbsm, 3},
  {"_Bd.get.nt.n_comps_ytbsm", (DL_FUNC)&Bd_get_nt_n_comps_ytbsm, 2},
  {"_Bd.set.nt.n_comps_ytbsm", (DL_FUNC)&Bd_set_nt_n_comps_ytbsm, 3},
  {"_Bd.get.n_par", (DL_FUNC)&Bd_get_n_par, 1},
  {"_Bd.set.n_par", (DL_FUNC)&Bd_set_n_par, 2},
  {"_Bd.get.n_POP", (DL_FUNC)&Bd_get_n_POP, 1},
  {"_Bd.set.n_POP", (DL_FUNC)&Bd_set_n_POP, 2},
  {"_Bd.get.n_samp", (DL_FUNC)&Bd_get_n_samp, 1},
  {"_Bd.set.n_samp", (DL_FUNC)&Bd_set_n_samp, 2},
  {"_Bd.get.N_ys", (DL_FUNC)&Bd_get_N_ys, 2},
  {"_Bd.set.N_ys", (DL_FUNC)&Bd_set_N_ys, 3},
  {"_Bd.get.nt.N_ys", (DL_FUNC)&Bd_get_nt_N_ys, 2},
  {"_Bd.set.nt.N_ys", (DL_FUNC)&Bd_set_nt_N_ys, 3},
  {"_Bd.get.n_ysb1_pars", (DL_FUNC)&Bd_get_n_ysb1_pars, 2},
  {"_Bd.set.n_ysb1_pars", (DL_FUNC)&Bd_set_n_ysb1_pars, 3},
  {"_Bd.get.nt.n_ysb1_pars", (DL_FUNC)&Bd_get_nt_n_ysb1_pars, 2},
  {"_Bd.set.nt.n_ysb1_pars", (DL_FUNC)&Bd_set_nt_n_ysb1_pars, 3},
  {"_Bd.next_param", (DL_FUNC)&Bd_R_next_param, 1},
  {"_Bd.nt.next_param", (DL_FUNC)&Bd_R_nt_next_param, 1},
  {"_Bd.get.nextpari", (DL_FUNC)&Bd_get_nextpari, 1},
  {"_Bd.set.nextpari", (DL_FUNC)&Bd_set_nextpari, 2},
  {"_Bd.populate", (DL_FUNC)&Bd_R_populate, 2},
  {"_Bd.nt.populate", (DL_FUNC)&Bd_R_nt_populate, 2},
  {"_Bd.get.Pr_PO_ytbs", (DL_FUNC)&Bd_get_Pr_PO_ytbs, 2},
  {"_Bd.set.Pr_PO_ytbs", (DL_FUNC)&Bd_set_Pr_PO_ytbs, 3},
  {"_Bd.get.nt.Pr_PO_ytbs", (DL_FUNC)&Bd_get_nt_Pr_PO_ytbs, 2},
  {"_Bd.set.nt.Pr_PO_ytbs", (DL_FUNC)&Bd_set_nt_Pr_PO_ytbs, 3},
  {"_Bd.get.pr_po_ytbsb1_pars", (DL_FUNC)&Bd_get_pr_po_ytbsb1_pars, 2},
  {"_Bd.set.pr_po_ytbsb1_pars", (DL_FUNC)&Bd_set_pr_po_ytbsb1_pars, 3},
  {"_Bd.get.nt.pr_po_ytbsb1_pars", (DL_FUNC)&Bd_get_nt_pr_po_ytbsb1_pars, 2},
  {"_Bd.set.nt.pr_po_ytbsb1_pars", (DL_FUNC)&Bd_set_nt_pr_po_ytbsb1_pars, 3},
  {"_Bd.get.roi", (DL_FUNC)&Bd_get_roi, 1},
  {"_Bd.set.roi", (DL_FUNC)&Bd_set_roi, 2},
  {"_Bd.get.roib1_pars", (DL_FUNC)&Bd_get_roib1_pars, 1},
  {"_Bd.set.roib1_pars", (DL_FUNC)&Bd_set_roib1_pars, 2},
  {"_Bd.get.sex", (DL_FUNC)&Bd_get_sex, 2},
  {"_Bd.set.sex", (DL_FUNC)&Bd_set_sex, 3},
  {"_Bd.get.nt.sex", (DL_FUNC)&Bd_get_nt_sex, 2},
  {"_Bd.set.nt.sex", (DL_FUNC)&Bd_set_nt_sex, 3},
  {"_Bd.get.sqrt_Pr_PO_ytbs", (DL_FUNC)&Bd_get_sqrt_Pr_PO_ytbs, 2},
  {"_Bd.set.sqrt_Pr_PO_ytbs", (DL_FUNC)&Bd_set_sqrt_Pr_PO_ytbs, 3},
  {"_Bd.get.nt.sqrt_Pr_PO_ytbs", (DL_FUNC)&Bd_get_nt_sqrt_Pr_PO_ytbs, 2},
  {"_Bd.set.nt.sqrt_Pr_PO_ytbs", (DL_FUNC)&Bd_set_nt_sqrt_Pr_PO_ytbs, 3},
  {"_Bd.sqrt_probs", (DL_FUNC)&Bd_R_sqrt_probs, 2},
  {"_Bd.nt.sqrt_probs", (DL_FUNC)&Bd_R_nt_sqrt_probs, 2},
  {"_Bd.get.tcap", (DL_FUNC)&Bd_get_tcap, 2},
  {"_Bd.set.tcap", (DL_FUNC)&Bd_set_tcap, 3},
  {"_Bd.get.nt.tcap", (DL_FUNC)&Bd_get_nt_tcap, 2},
  {"_Bd.set.nt.tcap", (DL_FUNC)&Bd_set_nt_tcap, 3},
  {"_Bd.get.temp_pars", (DL_FUNC)&Bd_get_temp_pars, 2},
  {"_Bd.set.temp_pars", (DL_FUNC)&Bd_set_temp_pars, 3},
  {"_Bd.get.nt.temp_pars", (DL_FUNC)&Bd_get_nt_temp_pars, 2},
  {"_Bd.set.nt.temp_pars", (DL_FUNC)&Bd_set_nt_temp_pars, 3},
  {"_Bd.get.temp_parsb1_pars", (DL_FUNC)&Bd_get_temp_parsb1_pars, 2},
  {"_Bd.set.temp_parsb1_pars", (DL_FUNC)&Bd_set_temp_parsb1_pars, 3},
  {"_Bd.get.nt.temp_parsb1_pars", (DL_FUNC)&Bd_get_nt_temp_parsb1_pars, 2},
  {"_Bd.set.nt.temp_parsb1_pars", (DL_FUNC)&Bd_set_nt_temp_parsb1_pars, 3},
  {"_Bd.unpack", (DL_FUNC)&Bd_R_unpack, 2},
  {"_Bd.nt.unpack", (DL_FUNC)&Bd_R_nt_unpack, 2},
  {"_Bd.get.ymat_atmost", (DL_FUNC)&Bd_get_ymat_atmost, 2},
  {"_Bd.set.ymat_atmost", (DL_FUNC)&Bd_set_ymat_atmost, 3},
  {"_Bd.get.nt.ymat_atmost", (DL_FUNC)&Bd_get_nt_ymat_atmost, 2},
  {"_Bd.set.nt.ymat_atmost", (DL_FUNC)&Bd_set_nt_ymat_atmost, 3},
  0
};


EXPORT void R_init_Bearded2(DllInfo* pInfo)
{
  R_SetArrayClass(ArrayClass_offarray);
  R_registerRoutines(pInfo, 0, 0, 0, extMethods);
}


EXPORT void R_init_libBearded2(DllInfo* pInfo)
{
  R_SetArrayClass(ArrayClass_offarray);
  R_registerRoutines(pInfo, 0, 0, 0, extMethods);
}


