1 bearded2__lglk: (TC19) Equality test on reals is not reliable
2 bearded2__populate: (TC16) Type mismatch in assignment: REAL receives REAL*8
3 bearded2__populate: (TC16) Type mismatch in assignment: REAL receives REAL*8
4 bearded2__populate: (TC16) Type mismatch in assignment: REAL receives REAL*8
5 bearded2__populate: (TC16) Type mismatch in assignment: REAL receives REAL*8
6 bearded2__populate: (TC16) Type mismatch in assignment: REAL receives REAL*8
7 n_log_p: (TC19) Equality test on reals is not reliable
